spring.application.name=crypto-trading

# App Version Control
application.version=${version}

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:crypto-trading;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# HikariCP Connection Pool (Spring Boot default)
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.pool-name=CryptoTradingPool

# Pool size (perfect for your 10s scheduler + API calls)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# H2 Console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Flyway Info
spring.flyway.url=jdbc:h2:mem:crypto-trading
spring.flyway.user=sa
spring.flyway.password=
spring.flyway.schemas=crypto-trading
spring.flyway.out-of-order=true

# Logging Info
logging.config=classpath:logging/log4j2.xml

# Redis Info
spring.data.redis.host=redis
spring.data.redis.port=6379

redis-lock.registry-key=crypto-trading
redis-lock.expire-after-in-millis=60000

# Scheduler Info
scheduler.run-price-aggregation-fixed-rate=10000

# http outbound
http.binance-ticker-base-url=https://api.binance.com
http.houbi-ticker-base-url=https://api.huobi.pro

