spring.application.name=crypto-trading

# App Version Control
application.version=${version}

# Spring DataSource Info
spring.datasource.url=jdbc:mysql://mysql_prod_true:3306/crypto-trading
spring.datasource.username=root
spring.datasource.password=root_password
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10

# Flyway Info
spring.flyway.url=jdbc:mysql://mysql_prod_true:3306/
spring.flyway.user=\${spring.datasource.username}
spring.flyway.password=\${spring.datasource.password}
spring.flyway.schemas=crypto-trading
spring.flyway.out-of-order=true

# Logging Info
logging.config=classpath:logging/log4j2.xml

# Redis Info
spring.data.redis.host=redis_prod_true
spring.data.redis.port=6379

redis-lock.registry-key=crypto-trading
redis-lock.expire-after-in-millis=60000

# Scheduler Info

